%YAML 1.1
---
# Snapcraft Recipe for gallery-dl
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: gallery-dl
title: gallery-dl (UNOFFICIAL)
license: GPL-2.0
base: core18
summary: Download image-galleries and -collections from several image hosting sites
description: |
  `gallery-dl` is a command-line program to download image-galleries and -collections from several image hosting sites (see [Supported Sites](https://github.com/mikf/gallery-dl/blob/master/docs/supportedsites.rst)). It is a cross-platform tool with many configuration options and powerful filenaming capabilities.

  **NOTE:** This is NOT an official distribution of gallery-dl, refer the [issue tracker](https://github.com/Lin-Buo-Ren/gallery-dl-snap/issues) for support.

icon: snap/gui/placeholder-brand.svg
adopt-info: gallery-dl

confinement: strict
grade: stable

plugs:
  # For `xdg-open` command access for opening OAuth authentication webpages
  desktop:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Network access
  network:

  # For network service for recieving OAuth callback tokens
  network-bind:

  # Configuration access
  # https://github.com/mikf/gallery-dl#configuration
  # FIXME: Waiting for Snap Store assertion
  #personal-files:
    #read:
    #- $HOME/.config/gallery-dl
    #- $HOME/.gallery-dl.conf
  #system-files:
    #read:
    #- /etc/gallery-dl.conf

parts:
  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  scriptlets:
    source: snap/local/scriptlets
    plugin: dump
    organize:
      '*': scriptlets/
    prime:
    - -*

  gallery-dl:
    after:
    - scriptlets

    source: https://github.com/mikf/gallery-dl.git
    source-depth: 100
    override-pull: |
      set -o nounset

      "${SNAPCRAFT_STAGE}"/scriptlets/gallery-dl-pull

    plugin: python

    # For formal release
    #source-tag: v1.7.0

  ffmpeg:
    plugin: nil
    stage-packages:
    - ffmpeg
    - libavcodec57
    - libavdevice57
    - libavfilter6
    - libavformat57
    - libavresample3
    - libavutil55
    - libpostproc54
    - libpulse0
    - libslang2
    - libswresample2
    - libswscale4

apps:
  gallery-dl:
    adapter: full
    command-chain:
    - bin/gallery-dl-launch
    command: bin/gallery-dl
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

      # Satisfy FFmpeg's libpulsecommon dependency
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

      HOME: $SNAP_USER_COMMON
